// Generated by CodeAssist from the project model. Review before you rely on it.

plugins {
    id("com.android.application")
}

android {
    namespace = "com.eternal.hexTocolor"
    compileSdk = 36

    defaultConfig {
        minSdk = 21
        targetSdk = 30
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}
